In [2]:
import pandas as pd

In [4]:
# read specific columns of csv file using Pandas
df_plant_cover = pd.read_csv(r"F:\wenqu\DOE_Arctic_project\2021_data\leafwtAK2021_site6A.csv", usecols = ['Site','quadrat', 'spp', 'cover', 'sla', 'la', 'LDMC']).dropna()
df_plant_cover

   Site  quadrat     spp  cover          sla      la         LDMC
2   S6A      1.0  castet   22.0   110.389016   4.824  0.377374784
3   S6A      1.0  chacal    2.0  112.9223744  24.730  0.229319372
4   S6A      1.0  dryint    8.0  106.4521363  19.683  0.225048685
5   S6A      1.0  eriang    9.0  102.2470434   7.781  0.473258706
6   S6A      1.0  erivag   28.0  35.14336918   1.961  1.853820598
..  ...      ...     ...    ...          ...     ...          ...
91  S6A     12.0   carex    7.0  51.93548387   1.127  0.487640449
92  S6A     12.0  castet    0.5  30.73200993   2.477   1.14978602
94  S6A     12.0  dryint   19.0      137.875  16.545  0.420315236
95  S6A     12.0  equspp   23.0  121.9408867  12.377  0.677118079
98  S6A     12.0  salarc    2.0  107.5936675  20.389  0.335814283

[78 rows x 7 columns]

In [8]:
df_plant_cover["site_quadrant"] = df_plant_cover['Site'].astype(str) + '_' + df_plant_cover['quadrat'].astype(int).astype(str)
df_plant_cover["site_quadrant_species"] = df_plant_cover['Site'].astype(str) + '_' + df_plant_cover['quadrat'].astype(int).astype(str) + '_' + df_plant_cover["spp"]
df_plant_cover

,Site,quadrat,spp,cover,sla,la,LDMC,site_quadrant,site_quadrant_species
2,S6A,1.0,castet,22.0,110.389016,4.824,0.377374784,S6A_1,S6A_1_castet
3,S6A,1.0,chacal,2.0,112.9223744,24.730,0.229319372,S6A_1,S6A_1_chacal
4,S6A,1.0,dryint,8.0,106.4521363,19.683,0.225048685,S6A_1,S6A_1_dryint
5,S6A,1.0,eriang,9.0,102.2470434,7.781,0.473258706,S6A_1,S6A_1_eriang
6,S6A,1.0,erivag,28.0,35.14336918,1.961,1.853820598,S6A_1,S6A_1_erivag
...,...,...,...,...,...,...,...,...,...
91,S6A,12.0,carex,7.0,51.93548387,1.127,0.487640449,S6A_12,S6A_12_carex
92,S6A,12.0,castet,0.5,30.73200993,2.477,1.14978602,S6A_12,S6A_12_castet
94,S6A,12.0,dryint,19.0,137.875,16.545,0.420315236,S6A_12,S6A_12_dryint
95,S6A,12.0,equspp,23.0,121.9408867,12.377,0.677118079,S6A_12,S6A_12_equspp
98,S6A,12.0,salarc,2.0,107.5936675,20.389,0.335814283,S6A_12,S6A_12_salarc

In [9]:
df1 = df_plant_cover.groupby(['Site','quadrat'], as_index=False)['cover'].sum()
df1.rename(columns={'cover': 'sum_cover'}, inplace=True)
df1["site_quadrant"] = df1['Site'].astype(str) + '_' + df1['quadrat'].astype(int).astype(str)
df1

   Site  quadrat  sum_cover site_quadrant
0   S6A      1.0      101.2         S6A_1
1   S6A      2.0      187.0         S6A_2
2   S6A      3.0      113.0         S6A_3
3   S6A      4.0        1.0         S6A_4
4   S6A      6.0       65.0         S6A_6
5   S6A      7.0       34.1         S6A_7
6   S6A      8.0      182.1         S6A_8
7   S6A      9.0       97.1         S6A_9
8   S6A     10.0      153.0        S6A_10
9   S6A     11.0       63.5        S6A_11
10  S6A     12.0       51.5        S6A_12

In [11]:
df_combine = pd.merge(df_plant_cover, df1, on ='site_quadrant')
df_combine

,Site_x,quadrat_x,spp,cover,sla,la,LDMC,site_quadrant,site_quadrant_species,Site_y,quadrat_y,sum_cover
0,S6A,1.0,castet,22.0,110.389016,4.824,0.377374784,S6A_1,S6A_1_castet,S6A,1.0,101.2
1,S6A,1.0,chacal,2.0,112.9223744,24.730,0.229319372,S6A_1,S6A_1_chacal,S6A,1.0,101.2
2,S6A,1.0,dryint,8.0,106.4521363,19.683,0.225048685,S6A_1,S6A_1_dryint,S6A,1.0,101.2
3,S6A,1.0,eriang,9.0,102.2470434,7.781,0.473258706,S6A_1,S6A_1_eriang,S6A,1.0,101.2
4,S6A,1.0,erivag,28.0,35.14336918,1.961,1.853820598,S6A_1,S6A_1_erivag,S6A,1.0,101.2
...,...,...,...,...,...,...,...,...,...,...,...,...
73,S6A,12.0,carex,7.0,51.93548387,1.127,0.487640449,S6A_12,S6A_12_carex,S6A,12.0,51.5
74,S6A,12.0,castet,0.5,30.73200993,2.477,1.14978602,S6A_12,S6A_12_castet,S6A,12.0,51.5
75,S6A,12.0,dryint,19.0,137.875,16.545,0.420315236,S6A_12,S6A_12_dryint,S6A,12.0,51.5
76,S6A,12.0,equspp,23.0,121.9408867,12.377,0.677118079,S6A_12,S6A_12_equspp,S6A,12.0,51.5
77,S6A,12.0,salarc,2.0,107.5936675,20.389,0.335814283,S6A_12,S6A_12_salarc,S6A,12.0,51.5

In [13]:
df = df_combine[['site_quadrant', 'site_quadrant_species', 'sla', 'la', 'LDMC', 'cover', 'sum_cover']]

df['percent_cover'] = df['cover'] / df['sum_cover']
df

C:\Users\15086\AppData\Local\Temp\ipykernel_22480\3524119068.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['percent_cover'] = df['cover'] / df['sum_cover']

,site_quadrant,site_quadrant_species,sla,la,LDMC,cover,sum_cover,percent_cover
0,S6A_1,S6A_1_castet,110.389016,4.824,0.377374784,22.0,101.2,0.217391
1,S6A_1,S6A_1_chacal,112.9223744,24.730,0.229319372,2.0,101.2,0.019763
2,S6A_1,S6A_1_dryint,106.4521363,19.683,0.225048685,8.0,101.2,0.079051
3,S6A_1,S6A_1_eriang,102.2470434,7.781,0.473258706,9.0,101.2,0.088933
4,S6A_1,S6A_1_erivag,35.14336918,1.961,1.853820598,28.0,101.2,0.276680
...,...,...,...,...,...,...,...,...
73,S6A_12,S6A_12_carex,51.93548387,1.127,0.487640449,7.0,51.5,0.135922
74,S6A_12,S6A_12_castet,30.73200993,2.477,1.14978602,0.5,51.5,0.009709
75,S6A_12,S6A_12_dryint,137.875,16.545,0.420315236,19.0,51.5,0.368932
76,S6A_12,S6A_12_equspp,121.9408867,12.377,0.677118079,23.0,51.5,0.446602
77,S6A_12,S6A_12_salarc,107.5936675,20.389,0.335814283,2.0,51.5,0.038835

In [15]:
df['weighted_sla'] = df['sla'].astype(float) * df['percent_cover'].astype(float)
df['weighted_la'] = df['la'].astype(float) * df['percent_cover'].astype(float)
df['weighted_LDMC'] = df['LDMC'].astype(float) * df['percent_cover'].astype(float)
df

C:\Users\15086\AppData\Local\Temp\ipykernel_22480\3663163155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weighted_sla'] = df['sla'].astype(float) * df['percent_cover'].astype(float)
C:\Users\15086\AppData\Local\Temp\ipykernel_22480\3663163155.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weighted_la'] = df['la'].astype(float) * df['percent_cover'].astype(float)
C:\Users\15086\AppData\Local\Temp\ipykernel_22480\3663163155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weighted_LDMC'] = df['LDMC'].astype(float) * df['percent_cover'].astype(float)

,site_quadrant,site_quadrant_species,sla,la,LDMC,cover,sum_cover,percent_cover,weighted_sla,weighted_la,weighted_LDMC
0,S6A_1,S6A_1_castet,110.389016,4.824,0.377374784,22.0,101.2,0.217391,23.997612,1.048696,0.082038
1,S6A_1,S6A_1_chacal,112.9223744,24.730,0.229319372,2.0,101.2,0.019763,2.231667,0.488735,0.004532
2,S6A_1,S6A_1_dryint,106.4521363,19.683,0.225048685,8.0,101.2,0.079051,8.415189,1.555968,0.017790
3,S6A_1,S6A_1_eriang,102.2470434,7.781,0.473258706,9.0,101.2,0.088933,9.093117,0.691986,0.042088
4,S6A_1,S6A_1_erivag,35.14336918,1.961,1.853820598,28.0,101.2,0.276680,9.723462,0.542569,0.512915
...,...,...,...,...,...,...,...,...,...,...,...
73,S6A_12,S6A_12_carex,51.93548387,1.127,0.487640449,7.0,51.5,0.135922,7.059192,0.153184,0.066281
74,S6A_12,S6A_12_castet,30.73200993,2.477,1.14978602,0.5,51.5,0.009709,0.298369,0.024049,0.011163
75,S6A_12,S6A_12_dryint,137.875,16.545,0.420315236,19.0,51.5,0.368932,50.866505,6.103981,0.155068
76,S6A_12,S6A_12_equspp,121.9408867,12.377,0.677118079,23.0,51.5,0.446602,54.459037,5.527592,0.302402
77,S6A_12,S6A_12_salarc,107.5936675,20.389,0.335814283,2.0,51.5,0.038835,4.178395,0.791806,0.013041

In [16]:
df_final = df.groupby(['site_quadrant']).agg({'weighted_sla':'sum','weighted_la':'sum','weighted_LDMC':'sum'})
df_final

               weighted_sla  weighted_la  weighted_LDMC
site_quadrant
S6A_1             97.993287     5.207945       0.855609
S6A_10            67.449010     0.387745       1.292386
S6A_11           109.157701    34.834276       0.492626
S6A_12           116.861497    12.600612       0.547956
S6A_2             97.318287    18.487914       0.380857
S6A_3             93.647522     7.037150       0.372395
S6A_4              0.000000     0.000000       0.321761
S6A_6             97.080215    11.953308       0.460407
S6A_7             96.397156    26.838906       0.413590
S6A_8             83.864292     6.134349       1.607404
S6A_9             77.645678     2.892549       0.488056

In [17]:
df_final.to_csv(r'F:\wenqu\DOE_Arctic_project\2021_statistic\site6_weighted_leaf.csv')